stages:
  - build 
  - deploy

before_script:
  # check git installation
  - which git || (apt-get update -qq && apt-get install --no-install-recommends -qqqy git)

  # Configure git to use Gitlab deploy keys instead of ssh/html
  # These must be created  and added as: https://docs.gitlab.com/ee/user/project/deploy_keys/index.html
  - git config --global url."https://$DEPLOY_NAME:$DEPLOY_KEY@gitlab.com/".insteadOf "git@gitlab.com:"
  - git config --global url."https://$DEPLOY_NAME:$DEPLOY_KEY@gitlab.com/".insteadOf "https://gitlab.com/" --add

# -------------------------
# Documentation
# -------------------------
# Build the documentation for the package

"Documentation":
  image: julia:1.7
  stage: build   
  
  # ----------------------------------------------------------------
  # TODO: remove this part once the versioned docs in 'make.jl' works
  artifacts:
    paths: 
      - documentation
    expire_in: 2 h
  # ----------------------------------------------------------------

  script:
    # Install Documenter 
    # Other dependecies may be already installed in a project 
    # within the 'docs/' folder
    - julia --project=docs/ -e 'using Pkg; Pkg.add("Documenter");'
    # Install the current package as 'dev'
    - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
    # Build the documentation
    - julia --project=docs/ docs/make.jl 

    # ----------------------------------------------------------------
    - mkdir -p documentation
    - mv docs/build/* documentation/
    # ----------------------------------------------------------------

  only:
    - master
    - tags

# Deploy the documentation
# ----------------------------------------------------------------
  stage: deploy
  
  dependencies: 
    - Documentation

  script:
    - mkdir -p public/latest
    - mv -v documentation/* public/latest/

  artifacts:
    paths:
      - public

  only:
    - master 
    - tags
# ----------------------------------------------------------------