name = "BaseMAT"
uuid = "f7345b97-8646-4350-bca5-2368100b77e2"
authors = ["andreapasquale94 <andrea.pasquale@outlook.it> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
